---
# supported providers Json and SQLite3 #
provider: "sqlite3"

# worlds which logged blocks broken and placed will be logged #
# world must be inserted here #
worlds:
- "world"
- ""

# if set to "true" the blockinspecter command will be enabled #
# if set to "false" the blockinspecter command will be disabled #
enable_command: "true"
...
